version: '3'
services:
  web:
    build: ./web
    image: trajano/web
    restart: always
    volumes:
    - "c:/www:/config"
#    volumes:#
#    - type: bind
#      source: "c:/www"
#      target: /config
#    - type: bind
#      source: "d:/dv/www"
#      target: /asdf/asdf/asdf
    environment:
    - EMAIL=arch@trajano.net
    - URL=trajano.net
    - SUBDOMAINS=www,i,site,gw,ms
    - TZ=America/Toronto
    depends_on:
    - mysql
    - site
    ports:
    - "80:80"
    - "443:443"
  sftpd:
    build: ./sftpd
    image: trajano/sftpd
    restart: always
    volumes:
    - site:/home/site/s
    ports:
    - "6022:22"
  site:
    build: ./site
    image: trajano/site
    restart: always
    volumes:
    - site:/site
  mysql:
    #image: mariadb:10.3
    build: ./mysql
    image: trajano/wpdb
    restart: always
    volumes:
    - wordpressdb:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wpadmin
    - MYSQL_PASSWORD=SecretAgentMan
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
#  wordpress:
 #   build: ./wordpress
 #   volumes:
 #   - type: bind
 #     source: "d:/dv/www/www"
 #     target: /www
    
#  hath:
#    build: ./hath
#    restart: always
#    ports:
#    - "12555:12555"
#    - target: 12555
#      published: 12555
#      protocol: tcp
#      mode: host
#    volumes:
#    - hath:/var/lib/hath
 #   environment:
 #   - CLIENT_ID=24108
 #   - CLIENT_KEY=cCws9MYJgcMqSf6waahW
 #   network_mode: "bridge"
#    #image: mariadb:10.3
#    networks:
#    - bridgedhath
#networks:
 # bridgedhath:
 #   driver: bridge
#    ipam:
#      config:
#      - subnet: 97.0.0.0/16
#    driver_opts:
#      com.docker.network.bridge.enable_ip_masquerade: "false"
#      com.docker.network.bridge.enable_icc: "false"
volumes:
  wordpressdb:
#  hath:
  site:
#- type: bind
#  source: mysqldata
#  target: d:/dv/mysql

#volumes:
#  www.trajano.net:
#    driver: local
#- type: bind
#  source: mysqldata
#  target: d:/dv/mysql
