#docker stack deploy -c docker-compose.yml --with-registry-auth trajano
#docker run -v noriko/s/letsencrypt:/etc/letsencrypt --volume-driver cifs trajano.net/web
version: '3.4'
services:
  # 4/kZkxXSsPXu7XlzItajkniSMhlptkhIjLVKJe7Aj+WjvbS35sdkEzjld8eqpO5c:$apr1$nAlpgWWz$m1r3URBT9dfTWr2sfZ24f.
  # 4/kZkxXSsPXu7XlzItajkniSMhlptkhIjLVKJe7Aj+WjvbS35sdkEzjld8eqpO5c
  # RhN5o7rN/PUiGySg0SBHr1HZaOy5hkG3bKnEeROU7BCmUqRhUwkzA271SK+RTdlb
  registry:
    image: registry:2
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      resources:
        limits:
          memory: 64M
      placement:
        constraints:
        - node.hostname==docker-engine
    volumes:
    - registry:/var/lib/registry
  web:
    image: trajano.net/web
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 10s
      resources:
        limits:
          memory: 32M
      placement:
        constraints:
        - node.hostname==docker-engine
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - letsencrypt:/etc/letsencrypt
    environment:
    - TZ=America/Toronto
    - HTTPVAL=true
    networks: 
    - public
    - default
volumes:
  registry:
    name: 'noriko/s/registry'
    driver: cifs
  letsencrypt:
    name: 'noriko/s/letsencrypt'
    driver: cifs
networks:
  public:
    external:
      name: public
