# This stack is used to build up the rest of the other stacks.  It contains the main entry point to access the registry and the
# intranet along with Portainer and the swarm dashboard which does not require any other stacks to be present.
#docker stack deploy -c docker-compose.yml --with-registry-auth trajano
#docker run -v noriko/s/letsencrypt:/etc/letsencrypt --volume-driver cifs trajano.net/web
version: '3.4'
services:
  # 4/kZkxXSsPXu7XlzItajkniSMhlptkhIjLVKJe7Aj+WjvbS35sdkEzjld8eqpO5c:$apr1$nAlpgWWz$m1r3URBT9dfTWr2sfZ24f.
  # 4/kZkxXSsPXu7XlzItajkniSMhlptkhIjLVKJe7Aj+WjvbS35sdkEzjld8eqpO5c
  # RhN5o7rN/PUiGySg0SBHr1HZaOy5hkG3bKnEeROU7BCmUqRhUwkzA271SK+RTdlb
  registry:
    image: registry:2
    deploy:
      restart_policy:
        condition: any
        delay: 10s
      resources:
        limits:
          memory: 64M
    volumes:
    - registry:/var/lib/registry
  web:
    image: trajano/nginx-letsencrypt
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 10s
      resources:
        limits:
          memory: 32M
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - letsencrypt:/etc/letsencrypt
    environment:
    - TZ=America/Toronto
    - EMAIL=arch@trajano.net
    - DOMAINS=trajano.net,gw.trajano.net,i.trajano.net,site.trajnao.net,ms.trajano.net
    networks:
    - public
    - default
    configs:
    - source: web_trajano_net
      target: /etc/nginx/conf.d/trajano.net.conf
    - source: web_site
      target: /etc/nginx/conf.d/site.trajano.net.conf
    - source: web_stream
      target: /etc/nginx/stream.d/stream.conf
    secrets:
    - source: htpasswd_registry
      target: /etc/nginx/conf.d/registry.htpasswd
      uid: '100'
      gid: '0'
      mode: 0400
  intranet:
    image: httpd:2.4.33-alpine
    ports:
    - "443"
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 10s
    volumes:
    - letsencrypt:/etc/letsencrypt:ro
    - intranet:/usr/local/apache2/htdocs:ro
    configs:
    - source: i-httpd.conf
      target: /usr/local/apache2/conf/httpd.conf
    - source: ca-cert-trajano.pem
      target: /etc/nginx/conf.d/trajano.net.conf
    environment:
    - TZ=America/Toronto
    networks:
    - default
    - intranet
  portainer:
    image: portainer/portainer
    command: --no-auth -H unix:///var/run/docker.sock
    deploy:
      placement:
        constraints:
         - node.role == manager
    networks:
    - intranet
    - default
    volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
    - portainer:/data
volumes:
  registry:
    name: 'noriko/s/registry'
    driver: cifs
  letsencrypt:
    name: 'noriko/s/letsencrypt'
    driver: cifs
  portainer:
    name: 'noriko/s/portainer'
    driver: cifs
  intranet:
    name: 'noriko/s/intranet'
    driver: cifs
networks:
  public:
    external:
      name: public
  intranet:
    external:
      name: intranet
configs:
  web_trajano_net:
    external: true
  web_site:
    external: true
  web_stream:
    external: true
secrets:
  htpasswd_registry:
    external: true
