#docker stack deploy -c docker-compose.yml --with-registry-auth trajano
version: '3.4'
services:
  intranet:
    build: ./intranet
    restart: always
    image: trajano.net/intranet
  grafana:
    build: ./support/grafana
    image: trajano.net/swarmprom-grafana
  prometheus:
    build: ./mon/prometheus
    image: trajano.net/swarmprom-prometheus
  smtp:
    build: ./smtp/smtp
    image: trajano.net/smtp
  wordpress:
    build: ./blog/wordpress
  wordpress-php:
    build: ./blog/wordpress-php
  jenkins:
    build: ./ci/jenkins
    image: trajano.net/jenkins
  sftpd:
    build: ./site/sftpd
  site:
    build: ./site/site
  mysql:
    build: ./db/mysql
networks:
  hath:
