#docker stack deploy -c docker-compose.yml --with-registry-auth trajano
version: '3.4'
services:
   # 4/kZkxXSsPXu7XlzItajkniSMhlptkhIjLVKJe7Aj+WjvbS35sdkEzjld8eqpO5c:$apr1$nAlpgWWz$m1r3URBT9dfTWr2sfZ24f.
  # 4/kZkxXSsPXu7XlzItajkniSMhlptkhIjLVKJe7Aj+WjvbS35sdkEzjld8eqpO5c
  # RhN5o7rN/PUiGySg0SBHr1HZaOy5hkG3bKnEeROU7BCmUqRhUwkzA271SK+RTdlb
  registry:
    image: registry:2
    deploy:
      restart_policy:
        condition: any
        delay: 10s
    volumes:
    - registry:/var/lib/registry
  web:
    build: ./web
    image: trajano.net/web
    restart: always
    deploy:
      restart_policy:
        condition: any
        delay: 10s
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - letsencrypt:/etc/letsencrypt
    environment:
    - EMAIL=arch@trajano.net
    - URL=trajano.net
    - SUBDOMAINS=www,i,site,gw,ms
    - CERTS=www.trajano.net,i.trajano.net,site.trajano.net,gw.trajano.net,ms.trajano.net
    - TZ=America/Toronto
    - HTTPVAL=true
  wordpress:
    build: ./wordpress
    image: trajano.net/blog
    ports:
    - "8080:443"
    volumes:
    - wordpress:/var/www/html
  portfolio:
    image: trajano.net/portfolio
    restart: always
    deploy:
      restart_policy:
        condition: any
        delay: 10s
    environment:
    - TZ=America/Toronto
    - HTTPVAL=true
  sftpd:
    build: ./sftpd
    image: trajano.net/sftpd
    restart: always
    volumes:
    - site:/home/site/s
    ports:
    - "6022:22"
  site:
    build: ./site
    image: trajano.net/site
    restart: always
    volumes:
    - site:/site
  mysql:
    #image: mariadb:10.3
    build: ./mysql
    image: trajano.net/wpdb
    restart: always
    volumes:
    #- "c:/wpdb:/var/lib/mysql"
    - wordpressdb:/var/lib/mysql:rw
    environment:
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wpadmin
    - MYSQL_PASSWORD=SecretAgentMan
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
  hath:
    build: ./hath
    image: trajano.net/hath
    restart: always
    ports:
    - target: 12555
      published: 12555
      protocol: tcp
      mode: host
    volumes:
    - hath:/var/lib/hath
volumes:
  site:
  wordpressdb:
    name: 'noriko/s/wpdb'
    driver: cifs
    driver_opts:
      cifsopts: vers=3.02,file_mode=0666,dir_mode=0777
  registry:
    name: 'noriko/s/registry'
    driver: cifs
    driver_opts:
      cifsopts: vers=3.02,file_mode=0666,dir_mode=0777
  www:
    name: 'noriko/s/www'
    driver: cifs
    driver_opts:
      cifsopts: vers=3.02,file_mode=0666,dir_mode=0777
  wordpress:
    name: 'noriko/s/wordpress'
    driver: cifs
    driver_opts:
      cifsopts: vers=3.02,file_mode=0666,dir_mode=0777
  hath:
    name: 'noriko/s/hath'
    driver: cifs
    driver_opts:
      cifsopts: vers=3.02,file_mode=0666,dir_mode=0777
  letsencrypt:
    name: 'noriko/s/letsencrypt'
    driver: cifs
    driver_opts:
      cifsopts: vers=3.02,file_mode=0666,dir_mode=0777,mfsymlinks
