version: '3.3'
services:
  web:
    build: ./web
    restart: always
    volumes:
    - d:/dv/www:/config
    environment:
    - EMAIL=arch@trajano.net
    - URL=trajano.net
    - SUBDOMAINS=www,i
    - TZ=America/Toronto
    depends_on:
    - mysql
    ports:
    - "80:80"
    - "443:443"
  mysql:
    #image: mariadb:10.3
    build: ./mysql
    restart: always
    volumes:
    - wordpressdb:/var/lib/mysql
    environment:
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wpadmin
    - MYSQL_PASSWORD=SecretAgentMan
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
#  hath:
#    #image: mariadb:10.3
#    build: ./hath
#    restart: always
#    ports:
#    - target: 12555
#      published: 12555
#      mode: host
#    volumes:
#    - hath:/var/lib/hath
#    environment:
#    - CLIENT_ID=24108
#    - CLIENT_KEY=cCws9MYJgcMqSf6waahW
#    networks:
#    - bridgedhath
#networks:
 # bridgedhath:
 #   driver: bridge
#    ipam:
#      config:
#      - subnet: 97.0.0.0/16
#    driver_opts:
#      com.docker.network.bridge.enable_ip_masquerade: "false"
#      com.docker.network.bridge.enable_icc: "false"
volumes:
  wordpressdb:
  hath:
#- type: bind
#  source: mysqldata
#  target: d:/dv/mysql

#volumes:
#  www.trajano.net:
#    driver: local
#- type: bind
#  source: mysqldata
#  target: d:/dv/mysql
