#docker stack deploy -c docker-compose.yml --with-registry-auth trajano
version: '3.4'
services:
   # 4/kZkxXSsPXu7XlzItajkniSMhlptkhIjLVKJe7Aj+WjvbS35sdkEzjld8eqpO5c:$apr1$nAlpgWWz$m1r3URBT9dfTWr2sfZ24f.
  # 4/kZkxXSsPXu7XlzItajkniSMhlptkhIjLVKJe7Aj+WjvbS35sdkEzjld8eqpO5c
  # RhN5o7rN/PUiGySg0SBHr1HZaOy5hkG3bKnEeROU7BCmUqRhUwkzA271SK+RTdlb
  registry:
    image: registry:2
    deploy:
      restart_policy:
        condition: any
        delay: 10s
    volumes:
    - registry:/var/lib/registry
  web:
    build: ./web
    image: trajano.net/web
    restart: always
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 10s
      placement:
        constraints:
        - node.hostname==docker-engine
    ports:
    - target: 80
      published: 80
      protocol: tcp
      mode: host
    - target: 443
      published: 443
      protocol: tcp
      mode: host
    volumes:
    - letsencrypt:/etc/letsencrypt
    environment:
    - EMAIL=arch@trajano.net
    - URL=trajano.net
    - SUBDOMAINS=www,i,site,gw,ms
    - CERTS=www.trajano.net,i.trajano.net,site.trajano.net,gw.trajano.net,ms.trajano.net
    - TZ=America/Toronto
    - HTTPVAL=true
    depends_on: 
    - portfolio
  wordpress:
    build: ./wordpress
    image: trajano.net/blog
    ports:
    - "8080:443"
    volumes:
    - wordpress:/var/www/html
  portfolio:
    image: trajano.net/portfolio
    restart: always
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 10s
      placement:
        constraints:
        - node.hostname!=docker-engine
    environment:
    - TZ=America/Toronto
  sftpd:
    build: ./sftpd
    image: trajano.net/sftpd
    restart: always
    volumes:
    - site:/home/site/s
    ports:
    - "6022:22"
  site:
    build: ./site
    image: trajano.net/site
    restart: always
    volumes:
    - site:/site
  mysql:
    #image: mariadb:10.3
    build: ./mysql
    image: trajano.net/wpdb
    restart: always
    volumes:
    #- "c:/wpdb:/var/lib/mysql"
    - wordpressdb:/var/lib/mysql:rw
    environment:
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wpadmin
    - MYSQL_PASSWORD=SecretAgentMan
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
#  hath:
#    build: ./hath
#    image: trajano.net/hath
#    restart: always
#    deploy:
#      mode: global
#      placement:
#        constraints:
#        - node.hostname==docker-engine
#    networks: 
#    - hosted
#    ports:
#    - target: 12555
#      published: 12555
#      protocol: tcp
#      mode: host
#    volumes:
#    - hath:/var/lib/hath
volumes:
  site:
  wordpressdb:
    name: 'noriko/s/wpdb'
    driver: cifs
  registry:
    name: 'noriko/s/registry'
    driver: cifs
  www:
    name: 'noriko/s/www'
    driver: cifs
  wordpress:
    name: 'noriko/s/wordpress'
    driver: cifs
  hath:
    name: 'noriko/s/hath'
    driver: cifs
  letsencrypt:
    name: 'noriko/s/letsencrypt'
    driver: cifs
networks:
  hosted:
    external:
      name: host