apiVersion: v1
kind: Pod
metadata:
  name: docker-registry
  namespace: kube-support
spec:
  hostNetwork: true
  containers:
  - name: registry
    image: registry:2
    env:
    - name: REGISTRY_HTTP_SECRET
      value: trajano
