#docker stack deploy -c docker-compose.yml --with-registry-auth trajano
version: '3.4'
services:
  hath:
    build: ./hath
    image: trajano.net/hath
    restart: always
    #network_mode: host
    deploy:
      placement:
        constraints:
        - node.hostname==docker-engine
    networks:
    - bridge
    ports:
    - target: 12555
      published: 12555
      protocol: tcp
      mode: host
    volumes:
    - hath:/var/lib/hath
volumes:
  hath:
    name: 'noriko/s/hath'
    driver: cifs
networks:
  bridge:
    external:
      name: bridge
