version: '3.4'
configs:
  node_rules:
    file: ./prometheus/rules/swarm_node.rules.yml
  task_rules:
    file: ./prometheus/rules/swarm_task.rules.yml
services:
  cadvisor:
    image: google/cadvisor
    networks:
    - local
    command: -logtostderr -docker_only
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /:/rootfs:ro
    - /var/run:/var/run
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  node-exporter:
    image: stefanprodan/swarmprom-node-exporter:v0.15.2
    networks:
    - local
    environment:
    - NODE_ID={{.Node.ID}}
    volumes:
    - /proc:/host/proc:ro
    - /sys:/host/sys:ro
    - /:/rootfs:ro
    - /etc/hostname:/etc/nodename
    command:
    - '--path.sysfs=/host/sys'
    - '--path.procfs=/host/proc'
    - '--collector.textfile.directory=/etc/node-exporter/'
    - '--collector.filesystem.ignored-mount-points=^/(sys|proc|dev|host|etc)($$|/)'
    # no collectors are explicitely enabled here, because the defaults are just fine,
    # see https://github.com/prometheus/node_exporter
    # disable ipvs collector because it barfs the node-exporter logs full with errors on my centos 7 vm's
    - '--no-collector.ipvs'
    deploy:
      mode: global
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  prometheus:
    image: trajano.net/swarmprom-prometheus
    networks:
    - mon
    command:
    - '--config.file=/etc/prometheus/prometheus.yml'
    - '--web.console.libraries=/etc/prometheus/console_libraries'
    - '--web.console.templates=/etc/prometheus/consoles'
    - '--storage.tsdb.path=/prometheus'
    - '--storage.tsdb.retention=24h'
    volumes:
    - prometheus:/prometheus
    configs:
    - source: node_rules
      target: /etc/prometheus/swarm_node.rules.yml
    - source: task_rules
      target: /etc/prometheus/swarm_task.rules.yml
    networks:
    - default
    - local
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
        - node.role != manager
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M

  alertmanager:
    image: stefanprodan/swarmprom-alertmanager:v0.14.0
    networks:
    - local
    environment:
    - SLACK_URL=https://hooks.slack.com/services/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
    - SLACK_CHANNEL=${SLACK_CHANNEL:-general}
    - SLACK_USER=${SLACK_USER:-alertmanager}
    command:
    - '--config.file=/etc/alertmanager/alertmanager.yml'
    - '--storage.path=/alertmanager'
    volumes:
      - alertmanager:/alertmanager
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role != manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  unsee:
    image: cloudflare/unsee:v0.8.0
    networks:
    - local
    environment:
    - "ALERTMANAGER_URIS=default:http://alertmanager:9093"
    deploy:
      mode: replicated
      replicas: 1

volumes:
  alertmanager:
    name: 'noriko/s/alertmanager'
    driver: cifs
  prometheus:
    name: 'noriko/s/prometheus'
    driver: cifs
networks:
  default:
    driver: overlay
    attachable: true
  local:
    attachable: false
