#docker stack deploy -c docker-compose.yml --with-registry-auth blog
#docker run -v noriko/s/letsencrypt:/etc/letsencrypt --volume-driver cifs trajano.net/web
version: '3.4'
services:
  wordpress:
    image: trajano.net/blog
    deploy:
      replicas: 2
      placement:
        constraints:
        - node.role != manager
    networks: 
    - public
    - default
    volumes:
    - wordpress:/var/www/html
  wordpress-php:
    image: trajano.net/blog-fpm
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 64M
      placement:
        constraints:
        - node.role != manager
    networks: 
    - default
    - db
    volumes:
    - wordpress:/var/www/html
  portfolio:
    image: trajano.net/portfolio
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 10s
      placement:
        constraints:
        - node.role != manager
    environment:
    - TZ=America/Toronto
    networks: 
    - public
volumes:
  wordpress:
    name: 'noriko/s/wordpress'
    driver: cifs
networks:
  public:
    external:
      name: public
  db:
    external:
      name: db_default
