version: '3.4'
services:
  mysql:
    image: mysql:8
    #command: --skip-grant-tables
    deploy:
      placement:
        constraints:
        - node.role != manager
      resources:
        limits:
          memory: 128M
#    ports:
#    - "3306:3306"
    volumes:
    - db-data:/var/lib/mysql:rw
    environment:
    - MYSQL_DATABASE=wordpress
    - MYSQL_USER=wpadmin
    - MYSQL_PASSWORD=SecretAgentMan
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    networks: 
    - backend
volumes:
  db-data:
    name: 'noriko/s/wpdb'
    driver: cifs:latest
networks:
  backend:
    external:
      name: backend
