#docker stack deploy -c docker-compose.yml --with-registry-auth jenkins
# docker-compose up -d --build
# docker service create --constraint node.hostname==docker-engine --publish published=12555,target=12555,mode=host --mount type=volume,source=noriko/s/hath,destination=/var/lib/hath,volume-driver=cifs trajano.net/hath
# docker run --restart always --publish published=12555,target=12555,mode=host --mount type=volume,source=noriko/s/hath,destination=/var/lib/hath,volume-driver=cifs trajano.net/hath
version: '3.4'
services:
  nexus:
    image: sonatype/nexus3
    environment:
    - NEXUS_CONTEXT=nexus
    volumes:
    - nexus-data:/nexus-data
    ports:
    - target: 8081
      published: 8081
      protocol: tcp
  jenkins:
    build: .
    image: trajano.net/jenkins
    ports:
    - target: 8080
      published: 18080
      protocol: tcp
    volumes:
    - jenkins_home:/var/jenkins_home
volumes:
  nexus-data:
    driver: sapk/plugin-gluster
    driver_opts:
      voluri: "store1:/nexus"
  jenkins_home:
    driver: sapk/plugin-gluster
    driver_opts:
      voluri: "store1:/jenkins"
