version: '3.4'
services:
  smtp:
    image: trajano.net/smtp
    configs:
    - source: main_cf
      target: /etc/postfix/main.cf
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 10s
      placement:
        constraints:
        - node.role != manager
    secrets:
    - sasl_passwd
    networks:
    - default
    - backend
networks:
  default:
    driver: overlay
    attachable: true
  backend:
    external:
      name: backend
secrets:
  sasl_passwd:
    external:
      name: sasl_passwd
configs:
  main_cf:
    external:
      name: postfix_main_cf
