version: '3.4'
services:
  smtp:
    image: namshi/smtp
    environment:
      RELAY_NETWORKS: ":10.0.0.0/16"
      SMARTHOST_ALIASES: "*"
      SMARTHOST_ADDRESS: in-v3.mailjet.com
      SMARTHOST_USER: 8f9243877229f6204f53aae00bc9c9d8
      SMARTHOST_PASSWORD: aa9e65721ecfbd7b0292f028e440fec2
    deploy:
      replicas: 2
      restart_policy:
        condition: any
        delay: 10s
      placement:
        constraints:
        - node.role != manager
      resources:
        limits:
          cpus: '0.50'
          memory: 50M
        reservations:
          cpus: '0.25'
          memory: 20M
    networks:
    - default
    - backend
networks:
  default:
    driver: overlay
    attachable: true
  backend:
    external:
      name: backend
