FROM uqlibrary/docker-crond
RUN yum install -q -q -y jre-headless && \
   wget -q https://github.com/eivindveg/HotSUploader/releases/download/v2.1.5/HotS.Replay.Uploader-2.1.5.jar -O hotsuploader.jar
